### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by lucke76** [supernova13892/whatsapp_stalker#7]
Hi, the extension stopped working today, seems that the js injection doesn't work anymore, could you fix it? The extension worked great in the last month

**Comment by iamnavid** [comment]
you could edit inject.js and change some class names:
example:
_2umId => _2rZZg
jN-F5 => _2zCfw
_2wP_Y => _3NWy8
_19RFN => _1wjpf
O90ur => _315-i

and some CSS changes in inject.css to show the btn.

**Comment by lucke76** [comment]
Thank you very much for the answer, i changed the class you suggested and button has reappared but the automatic contact selection doesn't work. I think it depends from this class _2EXPL the only one i didn't change. Also if i select manually a contact to record it doesn't work, the status are not saved in the log file.

Could you help me solve this? I would be very grateful

**Comment by lucke76** [comment]
I fixed the selction with the class _1wjpf now the only thing that doesn't work is the multi user selection, if i choose 2 user the selection is stuck with the first, but the status is recorded fine, do you have any suggestion to fix this?

**Comment by iamnavid** [comment]
if the searched contact do not clicked and opened I think you should change contact_span.parents(... to contact_span.parents("._2UaNq").

**Comment by supernova13892** [comment]
I will add a proper fix in the codebase by the weekend.
Mostly have been working on another way of data extraction which has proved to be more accurate than simply checking for elements on the page.
If someone can send a pull request, it will be great, otherwise expect a fix and more by the weekend,

**Comment by kurama98** [comment]
hi. i found out the button is no longer there

**Comment by kurama98** [comment]
Any update on this?

**Comment by supernova13892** [comment]
The fix has been updated. Thanks a lot @iamnavid for helping me with the classes, saved a lot of time.
I will try to focus on the other branch as depending on the selectors is not really a good idea in my view.
